languageCode = "en-gb"
title = "Matt White"
baseurl = "http://example.org/"

[params]
  name = "Matt Whitey"
  about = "IT Support Guru"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "Dribbble"
  icon = "dribbble"
  link = "#"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "#"
