languageCode = "en-gb"
title = "Matt White"
baseurl = "http://example.org/"

[params]
  name = "Matt White"
  about = "IT Support Analyst"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll emp
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/krangence"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/krangence"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "#"
